config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "projects#index"

  resources :projects, except: [:destroy] do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :conversation_id, presence: true
  validates :user_id,         presence: true
  validates :content,         presence: true

  belongs_to :conversation
  belongs_to :user
end

app/models/conversation_node.rb
class ConversationNode < ApplicationRecord
  validates :project_id, presence: true
  validates :conversationable_id, presence: true

  belongs_to :project
  belongs_to :conversationable, :polymorphic => true

  def user
    conversationable.user
  end

  def content
    conversationable.content
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :project_users
  has_many :users, through: :project_users
  has_many :conversation_nodes, -> { order(created_at: :desc) }
  has_many :statuses, through: :conversation_nodes, :source => :conversationable, :source_type => "Status"

  def add_user(user)
    ProjectUser.create(project: self, user: user)
  end

  def status
    statuses.order(created_at: :desc).first
  end

  def add_conversation_node(conversationable)
    ConversationNode.create(project: self, conversationable: conversationable)
  end
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  validates :project_id, presence: true
  validates :user_id,    presence: true

  belongs_to :project
  belongs_to :user
end

app/models/status.rb
class Status < ApplicationRecord
  validates :user_id, presence: true
  validates :content, presence: true

  has_one :conversation_node, as: :conversationable
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :project_users
  has_many :projects, through: :project_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ProjectsController

  def create
    comment = Comment.create(comment_params.merge(user: current_user))
    
    project.add_conversation_node(comment)

    redirect_to project_path(project), notice: "Comment added"
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    project.add_user(current_user)

    redirect_to projects_path
  end

  def show
    @project = project
    @comment = Comment.new
  end

  def update
    status = Status.create(content: status_params.fetch(:status), user: current_user)
    project.add_conversation_node(status)

    redirect_to project_path(project), notice: "Status updated"
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def status_params
    params.require(:project).permit(:status)
  end

  def project
    @project ||= current_user.projects.includes(conversation_nodes: [conversationable: [:user]]).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_node_helper.rb
module ConversationNodeHelper
  def format_node_content(node)
    if node.conversationable.class.name == "Status"
      "Changed project status to: #{node.content}"
    else
      node.content
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Your Projects</h1>

<% current_user.projects.each do |project| %>
  <%= link_to project.name, project_path(project) %><br>
<% end %>

<hr>

<%= link_to "Create new project", new_project_path %>

app/views/projects/new.html.erb
<h1>Create New Project<h1>

<%= form_for @project do |f| %>
  <%= f.label :name %>   
  <%= f.text_field :name %><br>

  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h1 id="project-name"><%= @project.name %></h1>

<div id="status">
  <b><%= @project.status&.content %></b>
</div>

<br>

<%= form_for @project do |f| %>
  <%= f.label :status, "Set project status" %><br> 
  <%= f.text_field :status, value: "" %>

  <%= f.submit "Save status" %>
<% end %>

<div id="conversation">
  <h3>Conversation</h3>

  <%= form_for @comment, url: project_comments_path(@project) do |f| %>
    <%= f.label :content, "Add comment" %><br> 
    <%= f.text_field :content %>

    <%= f.submit "Save" %>
  <% end %>

  <br>

  <% @project.conversation_nodes.each do |node| %>
    <%= format_node_content(node) %><br>
    <i><%= node.user.email %></i><br>
    <i><%= node.conversationable.created_at.strftime('%d %b %Y %H:%M:%S %Z')%></i><br>
    <br>
  <% end %>
</div>